services:
  invest-site:
    container_name: invest-site
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      - traefik.http.routers.invest-site.rule=Host(`invest.uno-ai.pw`)
      - traefik.http.routers.invest-site.entrypoints=websecure
      - traefik.http.routers.invest-site.tls=true
      - traefik.http.routers.invest-site.tls.certresolver=mytlschallenge
      - traefik.http.services.invest-site.loadbalancer.server.port=80

networks:
  traefik_network:
    external: true
